name: mouseodcolumns
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.7.3
  - numpy=1.24.4
  - pandas=2.0.3
  - python=3.8.16
  - python-box>=7.2.0
  - pip=24.2
  - scikit-image=0.21.0
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - seaborn=0.13.2
  - statsmodels=0.14.1
  - tqdm=4.67.1
  - pip:
      - scanimage-tiff-reader==1.4.1.4
