name: mouseodcolumns
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.11.7
  - python-box
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn=
  - statsmodels
  - tqdm
  - pip:
      - scanimage-tiff-reader
